config/routes.rb
Rails.application.routes.draw do
  resources :calendar_events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar_event.rb
class CalendarEvent < ApplicationRecord
  validates :description, presence: true
  validates :description, length: {maximum: 240}
  validates :occurs_at, presence: true

  def occurs_at_date
    occurs_at.to_date
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_events_controller.rb
class CalendarEventsController < ApplicationController
  before_action :set_calendar_event, only: [:show, :edit, :update, :destroy]
  before_action :fetch_dates, only: [:index, :create]

  # GET /calendar_events
  # GET /calendar_events.json
  def index
    @calendar_events = CalendarEvent.where(occurs_at: @date_range).order(:occurs_at).group_by(&:occurs_at_date)
    @calendar_event = CalendarEvent.new
  end

  # GET /calendar_events/1
  # GET /calendar_events/1.json
  def show
  end

  # GET /calendar_events/new
  def new
    @calendar_event = CalendarEvent.new
  end

  # GET /calendar_events/1/edit
  def edit
  end

  # POST /calendar_events
  # POST /calendar_events.json
  def create
    @calendar_event = CalendarEvent.new(calendar_event_params)
  end

  # PATCH/PUT /calendar_events/1
  # PATCH/PUT /calendar_events/1.json
  def update
    respond_to do |format|
      if @calendar_event.update(calendar_event_params)
        format.html { redirect_to @calendar_event, notice: 'Calendar event was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar_event }
      else
        format.html { render :edit }
        format.json { render json: @calendar_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendar_events/1
  # DELETE /calendar_events/1.json
  def destroy
    @calendar_event.destroy
    respond_to do |format|
      format.html { redirect_to calendar_events_url, notice: 'Calendar event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar_event
      @calendar_event = CalendarEvent.find(params[:id])
    end

    def fetch_dates
      @start_date = Date.current.to_date.beginning_of_month
      @date_range = (@start_date..@start_date.end_of_month)
      @dates = @date_range.to_a
      @dates.prepend(@dates.first - 1) until @dates.first.sunday?
      @dates.append(@dates.last + 1) until @dates.last.saturday?
    end

    # Only allow a list of trusted parameters through.
    def calendar_event_params
      params.require(:calendar_event).permit(:occurs_at, :description, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_events_helper.rb
module CalendarEventsHelper
end

app/views/calendar_events/_calendar_grid.html.erb
<% Date::DAYNAMES.each do |name| %>
  <div class="bg-gray-500 text-white p-3"><%= name %></div>
<% end %>
<%= render partial: "date", collection: dates, locals: { calendar_events: calendar_events, date_range: date_range } %>

app/views/calendar_events/_date.html.erb
<div class="flex flex-col justify-between border h-32 p-3 <%= "bg-gray-200" unless date_range.include? date %>">
  <span class="text-small font-bold"><%= date %></span>

  <% holidays = Holidays.on(date, Setting.first.holiday_region.downcase.to_sym) %>
  <% unless holidays.empty? %>
    <span class="bg-blue-600 rounded text-white px-4 py-2"><%= holidays.map { |h| h[:name] }.join(" ") %></span>
  <% end %>

  <% (calendar_events[date] || []).each do |calendar_event| %>
    <span class="bg-<%= calendar_event.color %>-700 rounded text-white px-4 py-2"><%= calendar_event.description %></span>
  <% end %>
</div>

app/views/calendar_events/_form.html.erb
<%= form_with(model: calendar_event, class: "m-8", data: {action: "calendar-events#submit", target: "calendar-events.form", resource: Rails.application.message_verifier("calendar_events").generate("CalendarEvent")}) do |form| %>
  <% if calendar_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calendar_event.errors.count, "error") %> prohibited this calendar_event from being saved:</h2>

      <ul>
        <% calendar_event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
    <%= form.label :occurs_at %>
    <%= form.date_field :occurs_at, class: "form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
  </div>
  
  <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
    <%= form.label :color %>
    <%= form.select :color, options_for_select(["yellow", "red", "green", "indigo"]), {}, class: "form-select block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
  </div>

  <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-textarea block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
  </div>

  <div class="mt-4">
    <%= form.submit class: "inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out" %>
  </div>
<% end %>

app/views/calendar_events/edit.html.erb
<h1>Editing Calendar Event</h1>

<%= render 'form', calendar_event: @calendar_event %>

<%= link_to 'Show', @calendar_event %> |
<%= link_to 'Back', calendar_events_path %>

app/views/calendar_events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="grid grid-cols-2 w-full">
  <div id="calendar-form" data-controller="calendar-events">
    <%= render "form", calendar_event: @calendar_event %>
  </div>
  <div id="settings-form" data-controller="settings">
    <%= form_with(model: Setting.first, method: :put, url: "#", class: "m-8", data: {signed_id: Setting.first.to_sgid.to_s, target: "settings.form"}) do |form| %>
      <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
        <%= form.label :holiday_region %>
        <%= form.country_select :holiday_region,
         {only: Holidays.available_regions.map(&:to_s).map(&:upcase)},
         class: "form-select block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5",
         data: {action: "change->settings#submit", reflex_dataset: "combined"} %>
      </div>
    <% end %>
  </div>
</div>
</div>

<div class="w-screen px-8 py-4">
  <div class="grid grid-cols-7 w-full" id="calendar-grid">
    <%= render partial: 'calendar_events/calendar_grid', locals: {dates: @dates, calendar_events: @calendar_events, date_range: @date_range} %>
  </div> 
</div>

app/views/calendar_events/new.html.erb
<h1>New Calendar Event</h1>

<%= render 'form', calendar_event: @calendar_event %>

<%= link_to 'Back', calendar_events_path %>

app/views/calendar_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Occurs at:</strong>
  <%= @calendar_event.occurs_at %>
</p>

<p>
  <strong>Description:</strong>
  <%= @calendar_event.description %>
</p>

<%= link_to 'Edit', edit_calendar_event_path(@calendar_event) %> |
<%= link_to 'Back', calendar_events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendula</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'stylesheets', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <%= yield %>
  </body>
</html>